@startuml

title DriveHub - Diagrama de clases

' Enumeracion de estado vehiculo
enum EstadoVehiculo {
    DISPONIBLE
    EN_ALQUILER
    EN_MANTENIMIENTO
    NECESITA_LIMPIEZA
}

abstract class Vehiculo {
    # matricula: string
    # estado: EstadoVehiculo
    # kilometraje: number
    tarifa: number
    cargo: number


    + getMatricula(): string
    + setMatricula(matricula: string): void
    + getEstado(): EstadoVehiculo
    + setEstado(estado: EstadoVehiculo): void
    + getKilometraje(): number
    + setKilometraje(kilometraje: number): void
    + abstract calcularTarifa(): number

    
}

class Compacto {
    - {static} TARIFA_BASE_DIA: number = 30
    - {static} CARGO_KM: number = 0.15
    - {static} KM_LIMITE_DIARIO: number = 100 

    + calcularTarifa(dias: number, kmRecorridos: number): number



             

}

class Sedan {
    - {static} TARIFA_BASE_DIA: number = 50
    - {static} CARGO_KM: number = 0.20

    + calcularTarifa(dias: number, kmRecorridos: number): number

}


class SUV {
    - {static} TARIFA_BASE_DIA: number = 80
    - {static} CARGO_SEGURO_DIA: number = 15
    - {static} CARGO_KM: number = 0.25
    - {static} KM_LIMITE_TOTAL: number = 500

    + calcularTarifa(dias: number, kmRecorridos: number): number


}


class Cliente {
    - nombre: string
    - email: string
    - reservas: Reserva []


}

class Reserva {
    - cliente: Cliente
    - vehiculo: Vehiculo
    - fechaDeInicio: Date
    - fechaDeFin: Date
    - kilometrajeInicial: number
    - kilometrajeFinal: number
    - costoTotal: number

    
}



' Relaciones de herencia
Vehiculo <|-- Compacto
Vehiculo <|-- Sedan
Vehiculo <|-- SUV






' Notas



@enduml